# Generated by Django 5.0.1 on 2024-02-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_order_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("CANCELED", "Canceled"),
                ],
                default="CREATED",
                max_length=20,
            ),
        ),
    ]
